version: '3'
services:
  site:
      working_dir: ${WORKING_DIR}
      build:
          context: docker/nginx
          dockerfile: Dockerfile
          args:
            - NGINX_TEMPLATE=${NGINX_TEMPLATE}
            - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
            - NGINX_ROOT=${NGINX_ROOT}
      volumes:
          - "./:${WORKING_DIR}"
      networks:
          - local
      env_file:
        - .env
      depends_on:
          - php
  php:
      working_dir: ${WORKING_DIR}
      build:
          context: docker/php
          dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
          - "./:${WORKING_DIR}"
          - "/tmp:/tmp"
      networks:
          - local
  postgres:
      image: postgres:9.6
      env_file:
          - .env
      volumes:
          - ./docker/postgres/data:/var/lib/postgresql/data
          - "/tmp:/tmp"
      networks:
          - local
      depends_on:
          - php
  adminer:
      image: adminer
      env_file:
        - .env
      networks:
          - local
      ports:
        - 8080:8080
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - network.host=0.0.0.0
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - local
    depends_on:
      - php
volumes:
  esdata1:
    driver: local
networks:
  local: